### ISSUE TITLE
About the function full2weak() and label_strong_T()

### ISSUE THREAD

**Issue by DeveloperZWK** [microsoft/ProDA#40]
Dear authors: Thanks for sharing your code with us. I do not understand why you use augmentation methods to the output probability of the encoder in the function full2weak() and label_strong_T(). How do these two functions help? I sincerely hope you can help me:>.

**Comment by JunXieFront** [comment]
> Dear authors: Thanks for sharing your code with us. I do not understand why you use augmentation methods to the output probability of the encoder in the function full2weak() and label_strong_T(). How do these two functions help? I sincerely hope you can help me:>.

Hi, I've got the same question, have you figured it out yet?

**Comment by panzhang0104** [comment]
@DeveloperZWK @JunXieFront， 
we use full2weak for the output probability of the EMA encoder, because the input of EMA is the full image, while the input of the basic model is weak augmentation. In order to use information from EMA, we need to use full2weak() function to align two outputs.

label_strong_T() is a function to align the pseudo label with the input image. The strong augmentation includes some spatial deformations, and we need to apply the same spatial deformations to the supervision.

**Comment by DeveloperZWK** [comment]
您好，邮件已收，谢谢！

**Comment by DeveloperZWK** [comment]
您好，邮件已收，谢谢！

**Comment by DeveloperZWK** [comment]
您好，邮件已收，谢谢！
